### ISSUE TITLE
Update version info for requirements

### ISSUE THREAD

**Issue by halvnok** [Stack-Box/stackbox-tutorials#1]
Flask app does not specify version of required packages. Because of this, the app no longer works as newer Socket.IO releases have invalidated the current code.

2 solutions:

1. Update the code to use the latest version of Socket.IO and keep it aligned with the latest release (undesirable because it will need to constantly be updated)
2. Add version to packages to lock at the version this code was intended for (becomes outdated but will still work)

**Comment by strangest-quark** [comment]
@halvnok I've freezed the requirements. This should fix the issue.
